config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"

  resources :curriculums
  resources :lessons
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/curriculum.rb
class Curriculum < ApplicationRecord
  has_many :lessons
end

app/models/lesson.rb
class Lesson < ApplicationRecord
  belongs_to :curriculum
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/curriculums_controller.rb
class CurriculumsController < ApplicationController
  def show
    @curriculum = Curriculum.find(params[:id])
  end

  def index
    @curriculums = Curriculum.all
  end

  def new
    @curriculum = Curriculum.new
  end

  def create
    @curriculum = Curriculum.new(curriculum_params)

    if @curriculum.save
      redirect_to curriculums_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def curriculum_params
    params.require(:curriculum).permit(:title, :purpose, :duration, :context, :lesson_hours)
  end
end

app/controllers/lessons_controller.rb
class LessonsController < ApplicationController

  def show
    @lesson = Lesson.find(params[:id])
  end

  def update
    @lesson = Lesson.find(params[:id])
    @lesson = update(lesson_params)
  end

  def destroy
    @lesson = Lesson.find(params[:id])
    @lesson.destroy
  end

  private

  def lesson_params
    params.require(:lesson).permit(:title, :description, :score)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :home ]

  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/curriculums/_lessons.html.erb
<h2 class="mx-5">Lessons</h2>
<div class="row">

  <% lessons.each do |lesson| %>
    <div class="col-4">
      <div class="bg-white d-flex flex-column justify-content-between p-2 border rounded-4 mt-1 text-decoration-none m-5 shadow h-100 d-inline-block">

        <div>
          <h3><strong><%= lesson.title %></strong></h3>
          <p class="mt-3"><%= lesson.description %></p>
        </div>

        <%= link_to "Begin Lesson", lesson_path(lesson), class:"ms-auto view-curriculum-btn" %>

      </div>
    </div>
  <% end %>
</div>

app/views/curriculums/index.html.erb
<%# first header with link on top right %>
<div class="d-flex justify-content-between text-left px-5">
  <h1>My Curricula</h1>
  <%= link_to 'Add new curriculum', new_curriculum_path, class: 'add-curriculum-btn mt-auto align-self-end' %>
</div>

<%# Container -> Loop each curriculum created by the form in new.html.erb %>
<div class="container">
  <% @curriculums.each do |curriculum| %>
    <%# bg-white = background white, justify-content-between %>
    <div class="bg-white shadow rounded p-3 m-3">
    <h2><%= curriculum.title %></h2>
    <%= link_to 'View curriculum', curriculum_path(curriculum), class: 'view-curriculum-btn mt-auto' %>
    </div>
  <% end %>
</div>

app/views/curriculums/new.html.erb
<%= simple_form_for(@curriculum) do |f| %>
  <%= f.input :title %>
  <%= f.input :purpose %>
  <%= f.input :duration %>
  <%= f.input :context %>
  <%= f.input :lesson_hours %>
  <%= f.submit %>
<% end %>

app/views/curriculums/show.html.erb
<div class="banner-background rounded-5 p-3 py-3 my-5 border shadow-sm">
  <div class="d-flex justify-content-between">
    <%= link_to "< All curriculums", curriculums_path, class: "text-declaration-none mx-5 justify-content-start" %>
  </div>
  <h1 class="mx-5"><%= @curriculum.title %></h1>
  <div class="d-flex mx-5">
    <p><strong>Purpose:</strong> &nbsp; </p>
    <%= @curriculum.purpose %>
  </div>
  <div class="d-flex mx-5">
    <p><strong>Context:</strong> &nbsp; </p>
    <%= @curriculum.context %>
  </div>
</div>

  <%= render 'lessons', lessons: @curriculum.lessons %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <title>Questlinguav2</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body><%= render "shared/navbar" %>
<%= render "shared/flashes" %>

    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to "#", class: "navbar-brand" do %>
      <%= image_tag "https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/logo.png" %>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item active">
            <%= link_to "Home", "#", class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Messages", "#", class: "nav-link" %>
          </li>
          <li class="nav-item dropdown">
          <a href="#" class="avatar" id="navbarDropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <%= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar", alt: "dropdown menu" %>
          </a>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Action", "#", class: "dropdown-item" %>
              <%= link_to "Another action", "#", class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>